name: Daily R devel and R patched build

on:
  workflow_dispatch:
  schedule:
    - cron:  '55 6 * * *'

jobs:

  daily-builds:
    name: ${{ matrix.config.r }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        config:
        - { r: 'devel' }
        - { r: 'next'  }

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build
      id: build
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64
#        platforms: linux/amd64,linux/arm64
        push: false
        load: true
        build-args: |
          R_VERSION=${{ matrix.config.r }}

    - name: Push
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64
#        platforms: linux/amd64,linux/arm64
        push: true
        build-args: |
          R_VERSION=${{ matrix.config.r }}
        tags: ${{ steps.build.outputs.tags }}
