name: Daily R devel and R patched build

on:
  workflow_dispatch:
  schedule:
    - cron:  '55 6 * * *'

jobs:

  daily-builds:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        config:
        - { r: 'devel',   tags: 'devel,4.2.0,4.2'                   }
        - { r: 'patched', tags: '4.1.2-patched,4.1-patched,patched' }

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Calculate tags
      id: tags
      run: |
        echo -n "::set-output name=tags::"
        echo ${{ matrix.config.tags }} |
        tr , '\n' |
        sed -e 's|^|ghcr.io/r-hub/r-minimal/r-minimal:|' |
        tr '\n' ,
        echo -n ${{ matrix.config.tags }} |
        tr , '\n' |
        sed -e 's|^|rhub/r-minimal:|' |
        tr '\n' ,

    - name: Check tags
      run: |
        echo "${{ steps.tags.outputs.tags }}"

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.tags.outputs.tags }}
